export const ADD_EMPLOYEES = 'ADD_EMPLOYEES';
export const SORT_BY_NAME_ASC = 'SORT_BY_NAME_ASC';
export const SORT_BY_NAME_DESC = 'SORT_BY_NAME_DESC';
export const SORT_BY_DATE_ASC = 'SORT_BY_DATE_ASC';
export const SORT_BY_DATE_DESC = 'SORT_BY_DATE_DESC';